baseurl: /
languageCode: en-us
title: Ricardo José R. Fontes
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Research
      url: /research/
      weight: 1
    - name: LinkedIn
      url: https://www.linkedin.com/in/ricardo-jose-fontes/
      weight: 2
    - name: Twitter
      url: https://twitter.com/ricardojrfontes
      weight: 3
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Ricardo José R. Fontes' webpage.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  site_logo: images/logo.png/
  highlightjsVersion: 9.12.0
  logo:
    alt: home
    height: 50
    url: /home.png/
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
